package mox_form;

import db.database;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class DetailMovie extends javax.swing.JFrame {

    public DetailMovie(String title, String username) {
        initComponents();
        setTitle("Detail Movie");
        setExtendedState(MAXIMIZED_BOTH);
        tf_username.setText(username);
        setBookmarkBtn(title, username);
        la_idMovie.setVisible(false);
        load_detail(title);
    }
    
    public void setBookmarkBtn(String title, String username) {
        try {
            String sql = "SELECT movie.title, user_bookmark.status "
                       + "FROM user_bookmark "
                       + "INNER JOIN movie "
                       + "ON user_bookmark.id_movie = movie.id_movie "
                       + "WHERE user_bookmark.user_username = '"+username+"' "
                       + "AND user_bookmark.status = 'Bookmarked' "
                       + "AND movie.title = '"+title+"' ";
            Connection conn = (Connection) database.getConn();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            if(res.next()) {
                ToggleBmark.setText("Bookmarked");
                ToggleBmark.setSelected(true);
            } else {
                ToggleBmark.setText("Bookmark");
                ToggleBmark.setSelected(false);
            }
            
        } catch (Exception e) {
        }
    }
    
    public ImageIcon getPoster(String url) {
        ImageIcon resizedImg = null;
        try {
            URL imgUrl = new URL(url);
            ImageIcon icon = new ImageIcon(imgUrl);
            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(305, 390, java.awt.Image.SCALE_SMOOTH);
            resizedImg = new ImageIcon(newImg);
        } catch (MalformedURLException e) {
        }
        
        return resizedImg;
    }
    
    public void load_detail(String title) {
        try {
            String sql = "SELECT movie.id_movie, movie.title, movie.date, movie.time, master_genre.genre_movie, "
                       + "director.nama_director, movie.plot, movie.poster, movie.rating, movie.jenis, "
                       + "movie_status.status, user.username "
                       + "FROM ((((movie "
                       + "INNER JOIN master_genre ON movie.genre = master_genre.id_master_genre) "
                       + "INNER JOIN director ON movie.director = director.id_director) "
                       + "INNER JOIN movie_status ON movie.status = movie_status.id_movie_status) "
                       + "INNER JOIN user ON movie.id_user = user.id_user) "
                       + "WHERE movie.title = '"+title+"' ";
            //System.out.println(sql);
            Connection conn = (Connection) database.getConn();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()) {
                la_idMovie.setText(res.getString("id_movie"));
                la_poster.setIcon(getPoster(res.getString("poster")));
                la_title.setText(res.getString("title"));
                la_genre.setText(res.getString("genre_movie"));
                ta_plot.setText(res.getString("plot"));
                la_director.setText("Director: " + res.getString("nama_director"));
                la_time.setText("Time: " + res.getString("time"));
            }
            
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navbar = new javax.swing.JPanel();
        NavLogo = new javax.swing.JLabel();
        hidePane = new javax.swing.JPanel();
        hide = new javax.swing.JLabel();
        soonPaneNav = new javax.swing.JPanel();
        soonNavbar = new javax.swing.JLabel();
        latestPaneNav = new javax.swing.JPanel();
        latestNavbar = new javax.swing.JLabel();
        genrePane = new javax.swing.JPanel();
        cbxGenre = new javax.swing.JComboBox<>();
        searchForm = new javax.swing.JTextField();
        tf_username = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        homePane = new javax.swing.JPanel();
        IconHome = new javax.swing.JLabel();
        bookmarkPane = new javax.swing.JPanel();
        IconBmark = new javax.swing.JLabel();
        streamPane = new javax.swing.JPanel();
        IconStream = new javax.swing.JLabel();
        logoutPane = new javax.swing.JPanel();
        IconLogout = new javax.swing.JLabel();
        hHomePane = new javax.swing.JPanel();
        hHomeText = new javax.swing.JLabel();
        hBmarkPane = new javax.swing.JPanel();
        hBmarkText = new javax.swing.JLabel();
        hStreamPane = new javax.swing.JPanel();
        hStreamText = new javax.swing.JLabel();
        hLogoutPane = new javax.swing.JPanel();
        hLogoutText = new javax.swing.JLabel();
        la_idMovie = new javax.swing.JLabel();
        Dasbor = new javax.swing.JScrollPane();
        VControlPanel = new javax.swing.JPanel();
        PosterPanel = new javax.swing.JPanel();
        la_poster = new javax.swing.JLabel();
        PhotoVideo = new javax.swing.JLabel();
        CastCrew = new javax.swing.JLabel();
        la_title = new javax.swing.JLabel();
        la_genre = new javax.swing.JLabel();
        PlotPane = new javax.swing.JScrollPane();
        ta_plot = new javax.swing.JTextArea();
        la_director = new javax.swing.JLabel();
        la_time = new javax.swing.JLabel();
        BookmarkPane = new javax.swing.JPanel();
        ToggleBmark = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Navbar.setBackground(new java.awt.Color(81, 196, 211));
        Navbar.setPreferredSize(new java.awt.Dimension(1366, 60));

        NavLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/nav-branding.png"))); // NOI18N
        NavLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavLogoMouseClicked(evt);
            }
        });

        hidePane.setBackground(new java.awt.Color(81, 196, 211));

        hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/Vector.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hidePaneLayout = new javax.swing.GroupLayout(hidePane);
        hidePane.setLayout(hidePaneLayout);
        hidePaneLayout.setHorizontalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        hidePaneLayout.setVerticalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        soonPaneNav.setBackground(new java.awt.Color(81, 196, 211));

        soonNavbar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        soonNavbar.setText("Coming Soon");
        soonNavbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soonNavbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                soonNavbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                soonNavbarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout soonPaneNavLayout = new javax.swing.GroupLayout(soonPaneNav);
        soonPaneNav.setLayout(soonPaneNavLayout);
        soonPaneNavLayout.setHorizontalGroup(
            soonPaneNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soonPaneNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soonNavbar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        soonPaneNavLayout.setVerticalGroup(
            soonPaneNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, soonPaneNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soonNavbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        latestPaneNav.setBackground(new java.awt.Color(81, 196, 211));

        latestNavbar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        latestNavbar.setText("Latest Movies");
        latestNavbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                latestNavbarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                latestNavbarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                latestNavbarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout latestPaneNavLayout = new javax.swing.GroupLayout(latestPaneNav);
        latestPaneNav.setLayout(latestPaneNavLayout);
        latestPaneNavLayout.setHorizontalGroup(
            latestPaneNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latestPaneNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(latestNavbar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        latestPaneNavLayout.setVerticalGroup(
            latestPaneNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, latestPaneNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(latestNavbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        genrePane.setBackground(new java.awt.Color(81, 196, 211));

        cbxGenre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Genre", "Action", "Horror", "Romance", "Thriller" }));
        cbxGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbxGenreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbxGenreMouseExited(evt);
            }
        });

        javax.swing.GroupLayout genrePaneLayout = new javax.swing.GroupLayout(genrePane);
        genrePane.setLayout(genrePaneLayout);
        genrePaneLayout.setHorizontalGroup(
            genrePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genrePaneLayout.setVerticalGroup(
            genrePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genrePaneLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(cbxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchForm.setText("Search here");
        searchForm.setPreferredSize(new java.awt.Dimension(69, 30));

        tf_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_username.setText("Username");

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addComponent(hidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NavLogo)
                .addGap(18, 18, 18)
                .addComponent(searchForm, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genrePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(latestPaneNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soonPaneNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213)
                .addComponent(tf_username)
                .addContainerGap())
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hidePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(soonPaneNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(latestPaneNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addComponent(genrePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tf_username)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Navbar, java.awt.BorderLayout.PAGE_START);

        SideBar.setBackground(new java.awt.Color(81, 196, 211));
        SideBar.setPreferredSize(new java.awt.Dimension(60, 708));

        homePane.setBackground(new java.awt.Color(81, 196, 211));

        IconHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/home page (1).png"))); // NOI18N
        IconHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconHomeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconHome, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookmarkPane.setBackground(new java.awt.Color(81, 196, 211));

        IconBmark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconBmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/Group 1.png"))); // NOI18N

        javax.swing.GroupLayout bookmarkPaneLayout = new javax.swing.GroupLayout(bookmarkPane);
        bookmarkPane.setLayout(bookmarkPaneLayout);
        bookmarkPaneLayout.setHorizontalGroup(
            bookmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconBmark, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        bookmarkPaneLayout.setVerticalGroup(
            bookmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookmarkPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconBmark)
                .addContainerGap())
        );

        streamPane.setBackground(new java.awt.Color(81, 196, 211));

        IconStream.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconStream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/Group 2.png"))); // NOI18N

        javax.swing.GroupLayout streamPaneLayout = new javax.swing.GroupLayout(streamPane);
        streamPane.setLayout(streamPaneLayout);
        streamPaneLayout.setHorizontalGroup(
            streamPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconStream, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        streamPaneLayout.setVerticalGroup(
            streamPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(streamPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconStream, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoutPane.setBackground(new java.awt.Color(81, 196, 211));

        IconLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mox_img/log out.png"))); // NOI18N

        javax.swing.GroupLayout logoutPaneLayout = new javax.swing.GroupLayout(logoutPane);
        logoutPane.setLayout(logoutPaneLayout);
        logoutPaneLayout.setHorizontalGroup(
            logoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        logoutPaneLayout.setVerticalGroup(
            logoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        hHomePane.setBackground(new java.awt.Color(81, 196, 211));

        hHomeText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hHomeText.setForeground(new java.awt.Color(102, 102, 102));
        hHomeText.setText("Home");
        hHomeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hHomeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hHomeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hHomeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hHomePaneLayout = new javax.swing.GroupLayout(hHomePane);
        hHomePane.setLayout(hHomePaneLayout);
        hHomePaneLayout.setHorizontalGroup(
            hHomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hHomePaneLayout.createSequentialGroup()
                .addComponent(hHomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        hHomePaneLayout.setVerticalGroup(
            hHomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hHomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hBmarkPane.setBackground(new java.awt.Color(81, 196, 211));

        hBmarkText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hBmarkText.setForeground(new java.awt.Color(102, 102, 102));
        hBmarkText.setText("Bookmark");
        hBmarkText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hBmarkTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hBmarkTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hBmarkTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hBmarkPaneLayout = new javax.swing.GroupLayout(hBmarkPane);
        hBmarkPane.setLayout(hBmarkPaneLayout);
        hBmarkPaneLayout.setHorizontalGroup(
            hBmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hBmarkPaneLayout.createSequentialGroup()
                .addComponent(hBmarkText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        hBmarkPaneLayout.setVerticalGroup(
            hBmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hBmarkText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hStreamPane.setBackground(new java.awt.Color(81, 196, 211));

        hStreamText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hStreamText.setForeground(new java.awt.Color(102, 102, 102));
        hStreamText.setText("Stream");
        hStreamText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hStreamTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hStreamTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hStreamTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hStreamPaneLayout = new javax.swing.GroupLayout(hStreamPane);
        hStreamPane.setLayout(hStreamPaneLayout);
        hStreamPaneLayout.setHorizontalGroup(
            hStreamPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hStreamPaneLayout.createSequentialGroup()
                .addComponent(hStreamText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        hStreamPaneLayout.setVerticalGroup(
            hStreamPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hStreamText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        hLogoutPane.setBackground(new java.awt.Color(81, 196, 211));

        hLogoutText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hLogoutText.setForeground(new java.awt.Color(102, 102, 102));
        hLogoutText.setText("Log Out");
        hLogoutText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hLogoutTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hLogoutTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hLogoutTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hLogoutPaneLayout = new javax.swing.GroupLayout(hLogoutPane);
        hLogoutPane.setLayout(hLogoutPaneLayout);
        hLogoutPaneLayout.setHorizontalGroup(
            hLogoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hLogoutPaneLayout.createSequentialGroup()
                .addComponent(hLogoutText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        hLogoutPaneLayout.setVerticalGroup(
            hLogoutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hLogoutText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        la_idMovie.setText("IDMOV");

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookmarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hBmarkPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hHomePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addComponent(streamPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hStreamPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addComponent(logoutPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hLogoutPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(la_idMovie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(hHomePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookmarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addComponent(hBmarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(streamPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(hStreamPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(hLogoutPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(la_idMovie)
                .addContainerGap(602, Short.MAX_VALUE))
        );

        getContentPane().add(SideBar, java.awt.BorderLayout.LINE_START);

        Dasbor.setPreferredSize(new java.awt.Dimension(1266, 915));

        VControlPanel.setBackground(new java.awt.Color(216, 227, 231));
        VControlPanel.setMaximumSize(new java.awt.Dimension(1366, 1366));
        VControlPanel.setPreferredSize(new java.awt.Dimension(1366, 909));

        PosterPanel.setBackground(new java.awt.Color(204, 204, 204));

        la_poster.setText("Poster Potrait");

        javax.swing.GroupLayout PosterPanelLayout = new javax.swing.GroupLayout(PosterPanel);
        PosterPanel.setLayout(PosterPanelLayout);
        PosterPanelLayout.setHorizontalGroup(
            PosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PosterPanelLayout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(la_poster, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PosterPanelLayout.setVerticalGroup(
            PosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(la_poster, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        PhotoVideo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhotoVideo.setForeground(new java.awt.Color(102, 102, 102));
        PhotoVideo.setText("Photos and Videos");

        CastCrew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CastCrew.setForeground(new java.awt.Color(102, 102, 102));
        CastCrew.setText("Cast And Crew");

        la_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        la_title.setText("Red Notice");

        la_genre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        la_genre.setText("Action | Adventure | Thrhiller");

        ta_plot.setBackground(new java.awt.Color(216, 227, 231));
        ta_plot.setColumns(20);
        ta_plot.setRows(5);
        ta_plot.setText("plot");
        ta_plot.setWrapStyleWord(true);
        ta_plot.setPreferredSize(new java.awt.Dimension(164, 98));
        PlotPane.setViewportView(ta_plot);

        la_director.setText("Director: ");

        la_time.setText("Time: ");

        ToggleBmark.setText("Bookmark");
        ToggleBmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleBmarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookmarkPaneLayout = new javax.swing.GroupLayout(BookmarkPane);
        BookmarkPane.setLayout(BookmarkPaneLayout);
        BookmarkPaneLayout.setHorizontalGroup(
            BookmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookmarkPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToggleBmark)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookmarkPaneLayout.setVerticalGroup(
            BookmarkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookmarkPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToggleBmark)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VControlPanelLayout = new javax.swing.GroupLayout(VControlPanel);
        VControlPanel.setLayout(VControlPanelLayout);
        VControlPanelLayout.setHorizontalGroup(
            VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PosterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VControlPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(la_time, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la_director, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VControlPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlotPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(la_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(la_genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PhotoVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CastCrew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BookmarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(514, 514, 514))
        );
        VControlPanelLayout.setVerticalGroup(
            VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VControlPanelLayout.createSequentialGroup()
                .addComponent(PosterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookmarkPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(la_genre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(VControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VControlPanelLayout.createSequentialGroup()
                        .addComponent(PhotoVideo)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(PlotPane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VControlPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CastCrew)))
                .addGap(18, 18, 18)
                .addComponent(la_director, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(la_time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );

        Dasbor.setViewportView(VControlPanel);

        getContentPane().add(Dasbor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
      // fungsi hover
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    // hide and show sidebar
    public void hideshow(JPanel menuhideandshow, boolean sidebarOn){
        if (sidebarOn == true){
            menuhideandshow.setPreferredSize(new Dimension(60, menuhideandshow.getHeight()));
        }else {
            menuhideandshow.setPreferredSize(new Dimension(195, menuhideandshow.getHeight()));
        }
    }
    
        

    boolean a;
    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // HIDE SIDEBAR CLICK
        
    
        
        if (a == true){
            hideshow(SideBar, a);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        }else {
            hideshow(SideBar, a);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }
    }//GEN-LAST:event_hideMouseClicked

    private void hideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseEntered
        // HIDE SIDEBAR ENTER - Salah anjing!
        changeColor(hidePane, new Color(216, 227, 231));
    }//GEN-LAST:event_hideMouseEntered

    private void hideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseExited
        // HIDE SIDEBAR EXIT
       changeColor(hidePane, new Color(81, 196, 211));
    }//GEN-LAST:event_hideMouseExited

    private void soonNavbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soonNavbarMouseClicked
        // btn coming soon navbar
        new SoonMovies(tf_username.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_soonNavbarMouseClicked

    private void soonNavbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soonNavbarMouseEntered
        // BUTTON COMING SOON
        changeColor(soonPaneNav, new Color(216, 227, 231));
    }//GEN-LAST:event_soonNavbarMouseEntered

    private void soonNavbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soonNavbarMouseExited
        // BUTTON COMING SOON
       changeColor(soonPaneNav, new Color(81, 196, 211));
    }//GEN-LAST:event_soonNavbarMouseExited

    private void latestNavbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latestNavbarMouseClicked
        // btn latest mov navbar
        new LatestMovies(tf_username.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_latestNavbarMouseClicked

    private void latestNavbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latestNavbarMouseEntered
        // BUTTON LATEST
       changeColor(latestPaneNav, new Color(216, 227, 231));
    }//GEN-LAST:event_latestNavbarMouseEntered

    private void latestNavbarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latestNavbarMouseExited
        // BUTTON LATEST
       changeColor(latestPaneNav, new Color(81, 196, 211));
    }//GEN-LAST:event_latestNavbarMouseExited

    private void cbxGenreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxGenreMouseEntered
        // BUTTON COMBO BOX
    }//GEN-LAST:event_cbxGenreMouseEntered

    private void cbxGenreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxGenreMouseExited
        // BUTTON COMBO BOX
    }//GEN-LAST:event_cbxGenreMouseExited

    private void IconHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconHomeMouseEntered

    }//GEN-LAST:event_IconHomeMouseEntered

    private void hHomeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hHomeTextMouseClicked
        // hidden btn sidebar home
        new UserDashboard(tf_username.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hHomeTextMouseClicked

    private void hHomeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hHomeTextMouseEntered
        // BUTTON BOOKMARK NEW
        changeColor(hHomePane, new Color(216, 227, 231));
    }//GEN-LAST:event_hHomeTextMouseEntered

    private void hHomeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hHomeTextMouseExited
        // BUTTON BOOKMARK NEW
        changeColor(hHomePane, new Color(81, 196, 211));
    }//GEN-LAST:event_hHomeTextMouseExited

    private void hBmarkTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hBmarkTextMouseClicked
        // TODO add your handling code here:
        new UserBookmark(tf_username.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hBmarkTextMouseClicked

    private void hBmarkTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hBmarkTextMouseEntered
        // TODO add your handling code here:
        changeColor(hBmarkPane, new Color(216, 227, 231));
    }//GEN-LAST:event_hBmarkTextMouseEntered

    private void hBmarkTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hBmarkTextMouseExited
        // TODO add your handling code here:
        changeColor(hBmarkPane, new Color(81, 196, 211));
    }//GEN-LAST:event_hBmarkTextMouseExited

    private void hStreamTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hStreamTextMouseClicked
        // TODO add your handling code here:
        StreamPage stream = new StreamPage();
        stream.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hStreamTextMouseClicked

    private void hStreamTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hStreamTextMouseEntered
        // BUTTON LOGIN NEW
        changeColor(hStreamPane, new Color(216, 227, 231));
    }//GEN-LAST:event_hStreamTextMouseEntered

    private void hStreamTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hStreamTextMouseExited
        // TODO add your handling code here:
        changeColor(hStreamPane, new Color(81, 196, 211));
    }//GEN-LAST:event_hStreamTextMouseExited

    private void hLogoutTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hLogoutTextMouseClicked
        // TODO add your handling code here:
        AppLogin backlogin = new AppLogin();
        backlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hLogoutTextMouseClicked

    private void hLogoutTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hLogoutTextMouseEntered
        // TODO add your handling code here:
        changeColor(hLogoutPane, new Color(216, 227, 231));
    }//GEN-LAST:event_hLogoutTextMouseEntered

    private void hLogoutTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hLogoutTextMouseExited
        // TODO add your handling code here:
        changeColor(hLogoutPane, new Color(81, 196, 211));
    }//GEN-LAST:event_hLogoutTextMouseExited

    private void NavLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavLogoMouseClicked
        // redirect to home
        new UserDashboard(tf_username.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NavLogoMouseClicked

    private void ToggleBmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleBmarkActionPerformed
        // btn bookmark
        String id_movie = la_idMovie.getText();
        String username = tf_username.getText();
        String query = "";
        String id_bookmark = "";
        //System.out.println(ToggleBmark.isSelected());
        
        // INSERT / UPDATE bookmark
        if (ToggleBmark.isSelected()) {
            try {
                String sql = "SELECT * FROM user_bookmark "
                           + "WHERE id_movie = '"+id_movie+"' "
                           + "AND user_username = '"+username+"' "
                           + "AND status = 'None' ";
                Connection conn = (Connection) database.getConn();
                Statement stat = conn.createStatement();
                ResultSet res = stat.executeQuery(sql);
                
                if(res.next()) {
                    id_bookmark = res.getString("id_bookmark");
                    query = "update";
                } else {
                    //id_bookmark = res.getString("id_bookmark");
                    query = "create";
                }
            } catch (Exception e) {
                
            }
            
            if(query.equals("update")) {
                try {
                    String sql = "UPDATE user_bookmark SET "
                               + "status = 'Bookmarked' "
                               + "WHERE id_bookmark = '"+id_bookmark+"' ";
                    Connection conn = (Connection) database.getConn();
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Movie Bookmarked");
                    this.dispose();
                    new UserBookmark(username).setVisible(true);
                } catch (Exception e) {
                }
            } else if (query.equals("create")) {
                try {
                    String sql = "INSERT INTO user_bookmark VALUES "
                               + "(default,'"+id_movie+"','"+username+"','Bookmarked') ";
                    Connection conn = (Connection) database.getConn();
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Movie Bookmarked");
                    this.dispose();
                    new UserBookmark(username).setVisible(true);
                } catch (Exception e) {
                }
            }
        }
        
        // unBookmark the movie
        if(!ToggleBmark.isSelected()) {
            try {
                String sql = "UPDATE user_bookmark SET "
                           + "status = 'None' "
                           + "WHERE user_username = '"+username+"' "
                           + "AND id_movie = '"+id_movie+"' ";
                Connection conn = (Connection) database.getConn();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Movie removed from Library");
                this.dispose();
                new UserBookmark(username).setVisible(true);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_ToggleBmarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookmarkPane;
    private javax.swing.JLabel CastCrew;
    private javax.swing.JScrollPane Dasbor;
    private javax.swing.JLabel IconBmark;
    private javax.swing.JLabel IconHome;
    private javax.swing.JLabel IconLogout;
    private javax.swing.JLabel IconStream;
    private javax.swing.JLabel NavLogo;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel PhotoVideo;
    private javax.swing.JScrollPane PlotPane;
    private javax.swing.JPanel PosterPanel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JToggleButton ToggleBmark;
    private javax.swing.JPanel VControlPanel;
    private javax.swing.JPanel bookmarkPane;
    private javax.swing.JComboBox<String> cbxGenre;
    private javax.swing.JPanel genrePane;
    private javax.swing.JPanel hBmarkPane;
    private javax.swing.JLabel hBmarkText;
    private javax.swing.JPanel hHomePane;
    private javax.swing.JLabel hHomeText;
    private javax.swing.JPanel hLogoutPane;
    private javax.swing.JLabel hLogoutText;
    private javax.swing.JPanel hStreamPane;
    private javax.swing.JLabel hStreamText;
    private javax.swing.JLabel hide;
    private javax.swing.JPanel hidePane;
    private javax.swing.JPanel homePane;
    private javax.swing.JLabel la_director;
    private javax.swing.JLabel la_genre;
    private javax.swing.JLabel la_idMovie;
    private javax.swing.JLabel la_poster;
    private javax.swing.JLabel la_time;
    private javax.swing.JLabel la_title;
    private javax.swing.JLabel latestNavbar;
    private javax.swing.JPanel latestPaneNav;
    private javax.swing.JPanel logoutPane;
    private javax.swing.JTextField searchForm;
    private javax.swing.JLabel soonNavbar;
    private javax.swing.JPanel soonPaneNav;
    private javax.swing.JPanel streamPane;
    private javax.swing.JTextArea ta_plot;
    private javax.swing.JLabel tf_username;
    // End of variables declaration//GEN-END:variables
}
